In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

In [2]:
import pandas as pd
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

import logging
logging.basicConfig(level=logging.INFO)

from src.parameters import ANIMALS, SAMPLING_FREQUENCY

In [8]:
blah = xr.open_mfdataset('../Processed-Data/HPa_03_04.nc', group='replicate/swr_stats')
blah.to_dataframe()

                                              area  csi  meanrate neuron_id  \
animal day epoch neuron_number tetrode_number
HPa    1   1     1             1                    NaN       NaN
                               2                    NaN       NaN
                               3                    NaN       NaN
                               4                    NaN       NaN
                               5                    NaN       NaN
                               6                    NaN       NaN
                               7                    NaN       NaN
                               8                    NaN       NaN
                               9                    NaN       NaN
                               10                   NaN       NaN
                               11                   NaN       NaN
                               12                   NaN       NaN
                               14                   NaN       NaN
                               15                   NaN       NaN
                               16                   NaN       NaN
                               17                   NaN       NaN
                               18                   NaN       NaN
                               20                   NaN       NaN
                 2             1                    NaN       NaN
                               2                    NaN       NaN
                               3                    NaN       NaN
                               4                    NaN       NaN
                               5                    NaN       NaN
                               6                    NaN       NaN
                               7                    NaN       NaN
                               8                    NaN       NaN
                               9                    NaN       NaN
                               10                   NaN       NaN
                               11                   NaN       NaN
                               12                   NaN       NaN
...                                            ...  ...       ...       ...
HPc    8   7     18            7                    NaN       NaN
                               8                    NaN       NaN
                               9                    NaN       NaN
                               10                   NaN       NaN
                               11                   NaN       NaN
                               12                   NaN       NaN
                               14                   NaN       NaN
                               15                   NaN       NaN
                               16                   NaN       NaN
                               17                   NaN       NaN
                               18                   NaN       NaN
                               20                   NaN       NaN
                 19            1                    NaN       NaN
                               2                    NaN       NaN
                               3                    NaN       NaN
                               4                    NaN       NaN
                               5                    NaN       NaN
                               6                    NaN       NaN
                               7                    NaN       NaN
                               8                    NaN       NaN
                               9                    NaN       NaN
                               10                   NaN       NaN
                               11                   NaN       NaN
                               12                   NaN       NaN
                               14                   NaN       NaN
                               15                   NaN       NaN
                               16                   NaN       NaN
                               17                   NaN       NaN
                               18                   NaN       NaN
                               20                   NaN       NaN

                                               numspikes  propbursts  \
animal day epoch neuron_number tetrode_number
HPa    1   1     1             1                     NaN         NaN
                               2                     NaN         NaN
                               3                     NaN         NaN
                               4                     NaN         NaN
                               5                     NaN         NaN
                               6                     NaN         NaN
                               7                     NaN         NaN
                               8                     NaN         NaN
                               9                     NaN         NaN
                               10                    NaN         NaN
                               11                    NaN         NaN
                               12                    NaN         NaN
                               14                    NaN         NaN
                               15                    NaN         NaN
                               16                    NaN         NaN
                               17                    NaN         NaN
                               18                    NaN         NaN
                               20                    NaN         NaN
                 2             1                     NaN         NaN
                               2                     NaN         NaN
                               3                     NaN         NaN
                               4                     NaN         NaN
                               5                     NaN         NaN
                               6                     NaN         NaN
                               7                     NaN         NaN
                               8                     NaN         NaN
                               9                     NaN         NaN
                               10                    NaN         NaN
                               11                    NaN         NaN
                               12                    NaN         NaN
...                                                  ...         ...
HPc    8   7     18            7                     NaN         NaN
                               8                     NaN         NaN
                               9                     NaN         NaN
                               10                    NaN         NaN
                               11                    NaN         NaN
                               12                    NaN         NaN
                               14                    NaN         NaN
                               15                    NaN         NaN
                               16                    NaN         NaN
                               17                    NaN         NaN
                               18                    NaN         NaN
                               20                    NaN         NaN
                 19            1                     NaN         NaN
                               2                     NaN         NaN
                               3                     NaN         NaN
                               4                     NaN         NaN
                               5                     NaN         NaN
                               6                     NaN         NaN
                               7                     NaN         NaN
                               8                     NaN         NaN
                               9                     NaN         NaN
                               10                    NaN         NaN
                               11                    NaN         NaN
                               12                    NaN         NaN
                               14                    NaN         NaN
                               15                    NaN         NaN
                               16                    NaN         NaN
                               17                    NaN         NaN
                               18                    NaN         NaN
                               20                    NaN         NaN

                                               spikewidth  is_significant  \
animal day epoch neuron_number tetrode_number
HPa    1   1     1             1                      NaN             NaN
                               2                      NaN             NaN
                               3                      NaN             NaN
                               4                      NaN             NaN
                               5                      NaN             NaN
                               6                      NaN             NaN
                               7                      NaN             NaN
                               8                      NaN             NaN
                               9                      NaN             NaN
                               10                     NaN             NaN
                               11                     NaN             NaN
                               12                     NaN             NaN
                               14                     NaN             NaN
                               15                     NaN             NaN
                               16                     NaN             NaN
                               17                     NaN             NaN
                               18                     NaN             NaN
                               20                     NaN             NaN
                 2             1                      NaN             NaN
                               2                      NaN             NaN
                               3                      NaN             NaN
                               4                      NaN             NaN
                               5                      NaN             NaN
                               6                      NaN             NaN
                               7                      NaN             NaN
                               8                      NaN             NaN
                               9                      NaN             NaN
                               10                     NaN             NaN
                               11                     NaN             NaN
                               12                     NaN             NaN
...                                                   ...             ...
HPc    8   7     18            7                      NaN             NaN
                               8                      NaN             NaN
                               9                      NaN             NaN
                               10                     NaN             NaN
                               11                     NaN             NaN
                               12                     NaN             NaN
                               14                     NaN             NaN
                               15                     NaN             NaN
                               16                     NaN             NaN
                               17                     NaN             NaN
                               18                     NaN             NaN
                               20                     NaN             NaN
                 19            1                      NaN             NaN
                               2                      NaN             NaN
                               3                      NaN             NaN
                               4                      NaN             NaN
                               5                      NaN             NaN
                               6                      NaN             NaN
                               7                      NaN             NaN
                               8                      NaN             NaN
                               9                      NaN             NaN
                               10                     NaN             NaN
                               11                     NaN             NaN
                               12                     NaN             NaN
                               14                     NaN             NaN
                               15                     NaN             NaN
                               16                     NaN             NaN
                               17                     NaN             NaN
                               18                     NaN             NaN
                               20                     NaN             NaN

                                               diff_from_baseline  \
animal day epoch neuron_number tetrode_number
HPa    1   1     1             1                              NaN
                               2                              NaN
                               3                              NaN
                               4                              NaN
                               5                              NaN
                               6                              NaN
                               7                              NaN
                               8                              NaN
                               9                              NaN
                               10                             NaN
                               11                             NaN
                               12                             NaN
                               14                             NaN
                               15                             NaN
                               16                             NaN
                               17                             NaN
                               18                             NaN
                               20                             NaN
                 2             1                              NaN
                               2                              NaN
                               3                              NaN
                               4                              NaN
                               5                              NaN
                               6                              NaN
                               7                              NaN
                               8                              NaN
                               9                              NaN
                               10                             NaN
                               11                             NaN
                               12                             NaN
...                                                           ...
HPc    8   7     18            7                              NaN
                               8                              NaN
                               9                              NaN
                               10                             NaN
                               11                             NaN
                               12                             NaN
                               14                             NaN
                               15                             NaN
                               16                             NaN
                               17                             NaN
                               18                             NaN
                               20                             NaN
                 19            1                              NaN
                               2                              NaN
                               3                              NaN
                               4                              NaN
                               5                              NaN
                               6                              NaN
                               7                              NaN
                               8                              NaN
                               9                              NaN
                               10                             NaN
                               11                             NaN
                               12                             NaN
                               14                             NaN
                               15                             NaN
                               16                             NaN
                               17                             NaN
                               18                             NaN
                               20                             NaN

                                               swr_modulation  swr_onset  \
animal day epoch neuron_number tetrode_number
HPa    1   1     1             1                          NaN        NaN
                               2                          NaN        NaN
                               3                          NaN        NaN
                               4                          NaN        NaN
                               5                          NaN        NaN
                               6                          NaN        NaN
                               7                          NaN        NaN
                               8                          NaN        NaN
                               9                          NaN        NaN
                               10                         NaN        NaN
                               11                         NaN        NaN
                               12                         NaN        NaN
                               14                         NaN        NaN
                               15                         NaN        NaN
                               16                         NaN        NaN
                               17                         NaN        NaN
                               18                         NaN        NaN
                               20                         NaN        NaN
                 2             1                          NaN        NaN
                               2                          NaN        NaN
                               3                          NaN        NaN
                               4                          NaN        NaN
                               5                          NaN        NaN
                               6                          NaN        NaN
                               7                          NaN        NaN
                               8                          NaN        NaN
                               9                          NaN        NaN
                               10                         NaN        NaN
                               11                         NaN        NaN
                               12                         NaN        NaN
...                                                       ...        ...
HPc    8   7     18            7                          NaN        NaN
                               8                          NaN        NaN
                               9                          NaN        NaN
                               10                         NaN        NaN

In [3]:
blah = xr.open_mfdataset('../Processed-Data/*.nc', group='replicate/swr_stats',
                         concat_dim=['blah'])
blah

ValueError: conflicting sizes for dimension 'concat_dim': length 1 on 'concat_dim' and length 48 on 'area'